name: bookia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  empty_widget: ^0.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  lottie: ^3.1.2
  pinput: ^5.0.0
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/image/
    - assets/icons/
  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/font/DMSerifDisplay-Regular.ttf